#!name=解锁ChatGPT-4
#!desc=解锁ChatGPT-4
#!homepage=https://raw.githubusercontent.com/yqc007/QuantumultX/master/NoMoCamProCrack.js
#!author=max guo
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/accu.png
[Script]
getOutButtons=type=http-response,pattern=^https?:\/\/ios\.chat\.openai\.com\/backend-api\/(accounts\/check\/|models),script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/ChatGPTPlusCrack.js,requires-body=1,max-size=0

[MITM]
hostname = %APPEND% ios.chat.openai.com
