#!name=Emby公益服分流
#!desc=TG个大公益服分流规则
#!homepage=https://raw.githubusercontent.com/marxguo/tool-config/refs/heads/main/module/module/company_rules.module
#!author=max guo
#!icon=https://www.en-plus.com.cn/public/uploads/images/20220228/8e7daf23d8c692041700ba3fb11935ef.png

[Role]
######################## DIRECT ########################
# git服务地址
IP-CIDR,10.30.50.43/32,公司内网JENKINS服务器,no-resolve
IP-CIDR,10.0.0.0/8,DIRECT