#!name=Emby公益服分流
#!desc=TG个大公益服分流规则
#!homepage=https://github.com/marxguo/tool-config
#!author=max guo

[Role]

DOMAIN-SUFFIX,ani.cappuccino.moe,DIRECT

DOMAIN-SUFFIX,media.nijigem.by,DIRECT

DOMAIN-SUFFIX,emby.bangumi.ca,DIRECT

DOMAIN-SUFFIX,embya.yusen.cyou,DIRECT

DOMAIN-SUFFIX,emby.taotu.ink,DIRECT

DOMAIN-SUFFIX,emby.dijia.de,DIRECT

DOMAIN-SUFFIX,test.inemby.us.ci,DIRECT

DOMAIN-SUFFIX,itsmygo.tv,DIRECT

DOMAIN-SUFFIX,emby.dremby.com,DIRECT
DOMAIN-SUFFIX,emby.huangmin.cc.cd,DIRECT
DOMAIN-SUFFIX,guangyacdn.com,DIRECT

DOMAIN-SUFFIX,emby.di0.uk,DIRECT

DOMAIN-SUFFIX,emby.staryuki.com,DIRECT

DOMAIN-SUFFIX,emby.kingemby.com,DIRECT








DOMAIN-SUFFIX,lite.cn2gias.uk,PROXY

DOMAIN-SUFFIX,emby.yusen.us.ci,PROXY
DOMAIN-SUFFIX,aaa.yusen6.ccwu.cc,PROXY
DOMAIN-SUFFIX,emby.yusen.cc.cd,PROXY

DOMAIN-SUFFIX,llyemby.cc.cd,PROXY

DOMAIN-SUFFIX,link00.okemby.org,PROXY
DOMAIN-SUFFIX,link01.okemby.org,PROXY

DOMAIN-SUFFIX,yykx.top,PROXY
