#!name=Emby公益服分流
#!desc=TG个大公益服分流规则
#!homepage=https://raw.githubusercontent.com/marxguo/tool-config/refs/heads/main/module/my_emby_roles.module
#!author=max guo

[Role]


######################## 直连 ########################
#  AniHub
DOMAIN-SUFFIX,ani.cappuccino.moe,DIRECT

#  二刺螈
DOMAIN-SUFFIX,media.nijigem.by,DIRECT

#  nyamedia
DOMAIN-SUFFIX,emby.bangumi.ca,DIRECT

#  予初
DOMAIN-SUFFIX,embya.yusen.cyou,DIRECT

#  乐蛙
DOMAIN-SUFFIX,emby.taotu.ink,DIRECT

#  乐观
DOMAIN-SUFFIX,emby.dijia.de,DIRECT

#  Nox
DOMAIN-SUFFIX,test.inemby.us.ci,DIRECT

#  ItsmyGo
DOMAIN-SUFFIX,itsmygo.tv,DIRECT

#  2F
DOMAIN-SUFFIX,emby.dremby.com,DIRECT
#  旧线路
DOMAIN-SUFFIX,emby.huangmin.cc.cd,DIRECT
DOMAIN-SUFFIX,guangyacdn.com,DIRECT

#  帝服
DOMAIN-SUFFIX,emby.di0.uk,DIRECT

#  星核
DOMAIN-SUFFIX,emby.staryuki.com,DIRECT

#  随时跑路
DOMAIN-SUFFIX,emby.kingemby.com,DIRECT








######################## 代理 ########################
#  Sntp（挂梯子）
DOMAIN-SUFFIX,lite.cn2gias.uk,PROXY

#  予初
DOMAIN-SUFFIX,emby.yusen.us.ci,PROXY
DOMAIN-SUFFIX,aaa.yusen6.ccwu.cc,PROXY
DOMAIN-SUFFIX,emby.yusen.cc.cd,PROXY

#  乐蛙
DOMAIN-SUFFIX,llyemby.cc.cd,PROXY

#  OK
DOMAIN-SUFFIX,link00.okemby.org,PROXY
DOMAIN-SUFFIX,link01.okemby.org,PROXY

#  营养快线
DOMAIN-SUFFIX,yykx.top,PROXY
