#
# 强制绕过打卡
# Quantumult X
#
# Author: marxguo
# Original:
# https://github.com/marxguo/tool-config
#

[rewrite_local]

# 获取打卡按钮状态
^http://oa\.en-plus\.com\.cn:8090/api/hrm/kq/attendanceButton/getOutButtons url script-response-body https://raw.githubusercontent.com/marxguo/tool-config/main/module/js/getOutButtons.js

# 获取定位/WiFi信息
^http://oa\.en-plus\.com\.cn:8090/api/hrm/kq/grouplocation/getLocationWifiInfo url script-response-body https://raw.githubusercontent.com/marxguo/tool-config/main/module/js/getLocationWifiInfo.js

# 打卡请求
^http://oa\.en-plus\.com\.cn:8090/api/hrm/kq/attendanceButton/punchButton url script-request-body https://raw.githubusercontent.com/marxguo/tool-config/main/module/js/punchButton.js


[mitm]

hostname = oa.en-plus.com.cn
